database:
  name: "showcase"
  owner:
    name: postgres
    password: root

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${database.name}
    username: ${database.owner.name}
    password: ${database.owner.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: 'create-drop'
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy # replaces SpringPhysicalNamingStrategy
